#!/bin/bash

if [ `id -u` -ne '0' ]; then
    dialog \
	--backtitle 'Virtual Machine Kicker' \
	--title 'Error' \
	--infobox 'This script must be run as root\nYou are not root. Too bad.\nTry sudo next time.' 5 40
    exit 1
fi

VMS='m01.example.com n01.example.com n02.example.com'

CHOICES=`mktemp`

dialog \
    --backtitle 'Virtual Machine Kicker' \
    --no-tags \
    --title 'Select the VMs to kick' \
    --checklist 'Virtual Machines' 10     50    10 \
    m01 m01.example.com off \
    n01 n01.example.com off \
    n02 n02.example.com off \
    --title "Confirm" \
    --yesno "Start VMs after kick?" 6 30 2>${CHOICES}

STARTVMS=${?}

pushd /var/lib/libvirt/images/ >/dev/null 2>&1

for img in $(<${CHOICES}); do
    i="${img}.example.com"
    virsh destroy ${i}
    rm -f ${i}
    qemu-img create -f qcow2 -b `pwd -P`/${i}-base ${i}
    if [ "${STARTVMS}" -eq "0" ]; then
	virsh start ${i}
    fi
    echo "---"
done

rm $CHOICES
